const jobTransitions = {
  "Software Engineer": ["Senior Software Engineer", "Tech Lead", "Engineering Manager", "CTO"],
  "Data Scientist": ["Senior Data Scientist", "AI Engineer", "Head of Data Science", "Chief Data Officer"],
  "Machine Learning Engineer": ["AI Engineer", "Deep Learning Specialist", "ML Architect", "AI Research Scientist"],
  "Frontend Developer": ["Senior Frontend Developer", "UI/UX Engineer", "Frontend Architect", "Head of UI/UX"],
  "Backend Developer": ["Senior Backend Developer", "System Architect", "Engineering Manager", "CTO"],
  "Full Stack Developer": ["Senior Full Stack Developer", "Software Architect", "VP of Engineering", "CTO"],
  "Web Developer": ["Senior Web Developer", "Lead Web Developer", "Web Architect", "Head of Web Development"],
  "DevOps Engineer": ["Senior DevOps Engineer", "Cloud Architect", "Head of DevOps", "CTO"],
  "Cybersecurity Analyst": ["Security Engineer", "Cybersecurity Architect", "CISO", "VP of Security"],
  "Cloud Engineer": ["Cloud Architect", "Cloud Security Engineer", "Head of Cloud Engineering", "CTO"],
  "AI Engineer": ["Senior AI Engineer", "AI Research Scientist", "Director of AI", "Chief AI Officer"],
  "Digital Marketing Manager": ["Senior Marketing Manager", "Head of Digital Marketing", "VP of Marketing", "CMO"],
  "SEO Specialist": ["Senior SEO Manager", "Head of SEO", "VP of Digital Marketing", "CMO"],
  "Content Strategist": ["Senior Content Strategist", "Head of Content Marketing", "VP of Content Strategy", "CMO"],
  "Product Manager": ["Senior Product Manager", "Director of Product", "VP of Product", "CPO"],
  "UI/UX Designer": ["Senior UX Designer", "Design Lead", "Head of UX", "VP of Design"],
  "Business Analyst": ["Senior Business Analyst", "Product Owner", "VP of Business Strategy", "CEO"],
  "IT Support Specialist": ["IT Support Manager", "IT Director", "CIO", "CEO"],
  "System Administrator": ["Senior SysAdmin", "IT Manager", "Head of IT Operations", "CIO"],
  "Network Engineer": ["Senior Network Engineer", "Network Architect", "Head of IT Infrastructure", "CIO"],
  "Data Analyst": ["Senior Data Analyst", "Business Intelligence Lead", "Head of Data Analytics", "Chief Data Officer"],
  "Finance Analyst": ["Senior Finance Analyst", "Finance Manager", "CFO", "CEO"],
  "Software Architect": ["Principal Software Architect", "VP of Engineering", "CTO", "CEO"],
  "Game Developer": ["Senior Game Developer", "Game Director", "Head of Game Design", "CTO"],
  "Sales Manager": ["Senior Sales Manager", "Head of Sales", "VP of Sales", "Chief Revenue Officer"],
  "E-commerce Manager": ["Senior E-commerce Manager", "Head of E-commerce", "VP of E-commerce", "CMO"],
  "Robotics Engineer": ["Senior Robotics Engineer", "Automation Architect", "Head of Robotics", "CTO"],
  "Electrical Engineer": ["Senior Electrical Engineer", "Chief Electrical Engineer", "CTO", "CEO"],
  "Mechanical Engineer": ["Senior Mechanical Engineer", "Lead Engineer", "VP of Engineering", "CEO"],
  "Biomedical Engineer": ["Senior Biomedical Engineer", "Medical Technology Director", "CTO", "CEO"],
  "Supply Chain Manager": ["Senior Supply Chain Manager", "Head of Logistics", "VP of Supply Chain", "COO"],
  "Legal Consultant": ["Senior Legal Advisor", "Head of Legal", "VP of Legal", "General Counsel"],
  "Game Designer": ["Senior Game Designer", "Game Director", "VP of Game Development", "CEO"],
  "HR Manager": ["Senior HR Manager", "Director of HR", "VP of HR", "Chief People Officer"],
  "Operations Manager": ["Senior Operations Manager", "Director of Operations", "VP of Operations", "COO"],
  "Graphic Designer": ["Senior Graphic Designer", "Art Director", "Creative Director", "VP of Design"],
  "Content Writer": ["Senior Content Writer", "Content Lead", "Head of Content", "VP of Communications"],
  "AI Research Scientist": ["AI Engineer", "AI Professor", "Head of AI Research", "Chief AI Officer"],
  "Cloud Security Engineer": ["Cloud Architect", "Head of Cloud Security", "CISO", "VP of Security"],
  "Security Analyst": ["Senior Security Analyst", "Security Engineer", "CISO", "VP of Security"],
  "Penetration Tester": ["Senior Pentester", "Security Consultant", "Cybersecurity Director", "CISO"],
};

export default jobTransitions;
